import createNec2Module from "../../public/wasm/nec2c.js";

/**
 * NEC2 Context API Wrapper
 */
export class Nec2Context {
  private wires: any[] = [];
  private sources: any[] = [];
  private frequency: number = 430.0;
  private groundHeight: number | null = null;
  private material: string = "aluminum";
  private patternCache: Map<string, number> = new Map();
  private impedanceCache: Map<number, {re: number, im: number}> = new Map();
  private currents: Array<{mag: number, phase: number, x: number, y: number, z: number, length: number}> = [];
  private maxGainDbi: number = 0;

  constructor() {}

  initialize(num_wires: number) {
    this.wires = [];
    this.sources = [];
    this.patternCache.clear();
    this.impedanceCache.clear();
    this.currents = [];
  }

  add_wire(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number, radius: number, segments: number, tag: number) {
    this.wires.push({ x1, y1, z1, x2, y2, z2, radius, segments, tag });
  }

  set_frequency(mhz: number) { this.frequency = mhz; }
  set_ground(height_lambda: number) { this.groundHeight = height_lambda; }
  set_material(mat: string) { this.material = mat; }
  
  add_voltage_source(tag: number, seg_on_wire: number, real: number, imag: number) {
    this.sources.push({ tag, seg: seg_on_wire, real, imag });
  }

  async calculate() {
    const Module = await (createNec2Module as any)({
      locateFile: (path: string) => `/wasm/${path}`,
      print: () => {}, 
      printErr: () => {}, 
    });

    let nec = `CM Generated by Nec2Context API\nCE\n`;
    for (const w of this.wires) {
      nec += `GW ${w.tag} ${w.segments} ${w.x1.toFixed(5)} ${w.y1.toFixed(5)} ${w.z1.toFixed(5)} ${w.x2.toFixed(5)} ${w.y2.toFixed(5)} ${w.z2.toFixed(5)} ${w.radius.toFixed(6)}\n`;
    }
    
    nec += `GE ${this.groundHeight !== null && this.groundHeight > 0 ? 1 : 0}\n`;
    if (this.material === "aluminum") nec += `LD 5 0 0 0 3.5E7\n`;
    else if (this.material === "stainless_steel") nec += `LD 5 0 0 0 1.1E6\n`;

    if (this.groundHeight !== null && this.groundHeight > 0) {
      nec += `GN 0 0 0 0 13 0.005\n`;
    } else {
      nec += `GN -1\n`;
    }

    for (const s of this.sources) {
      nec += `EX 0 ${s.tag} ${s.seg} 0 ${s.real.toFixed(2)} ${s.imag.toFixed(2)}\n`;
    }
    
    nec += `FR 0 1 0 0 ${this.frequency.toFixed(3)} 0\n`;
    nec += `RP 0 37 73 1 0 0 5 5\n`;
    nec += `EN\n`;

    const inputPath = "/input.nec";
    const outputPath = "/output.out";
    Module.FS.writeFile(inputPath, nec);

    try {
      Module.callMain(["-i", inputPath, "-o", outputPath]);
    } catch (e: any) {
      if (e.name !== "ExitStatus" && e.constructor.name !== "ExitStatus") throw e;
    }

    if (!Module.FS.analyzePath(outputPath).exists) throw new Error("NEC2 failed.");
    const outputData = Module.FS.readFile(outputPath, { encoding: "utf8" });
    this.parseResults(outputData);
  }

  private parseResults(data: string) {
    this.patternCache.clear();
    this.impedanceCache.clear();
    this.currents = [];
    this.maxGainDbi = -99;
    const lines = data.split("\n");
    let section: 'none' | 'impedance' | 'pattern' | 'current' = 'none';

    for (let line of lines) {
        line = line.trim();
        if (line.includes("ANTENNA INPUT PARAMETERS")) { section = 'impedance'; continue; }
        if (line.includes("RADIATION PATTERNS")) { section = 'pattern'; continue; }
        if (line.includes("CURRENTS AND LOCATION")) { section = 'current'; continue; }

        if (section === 'impedance') {
            const parts = line.split(/\s+/);
            if (parts.length >= 6 && !isNaN(parseFloat(parts[0]))) {
                this.impedanceCache.set(this.sources[0]?.tag || 1, {re: parseFloat(parts[parts.length - 2]), im: parseFloat(parts[parts.length - 1])});
            }
        }
        if (section === 'current') {
            const parts = line.split(/\s+/);
            if (parts.length >= 10 && !isNaN(parseInt(parts[0]))) {
                this.currents.push({
                    x: parseFloat(parts[2]), y: parseFloat(parts[3]), z: parseFloat(parts[4]),
                    length: parseFloat(parts[5]), mag: parseFloat(parts[8]), phase: parseFloat(parts[9])
                });
            }
        }
        if (section === 'pattern') {
            const parts = line.split(/\s+/);
            if (parts.length >= 5 && !isNaN(parseFloat(parts[0])) && !isNaN(parseFloat(parts[1]))) {
                const rawGainDbi = parseFloat(parts[4]);
                if (rawGainDbi > this.maxGainDbi) this.maxGainDbi = rawGainDbi;
                const gain = Math.pow(10, Math.max(-40, rawGainDbi) / 10);
                this.patternCache.set(`${Math.round(parseFloat(parts[0]))},${Math.round(parseFloat(parts[1]))}`, gain);
            }
        }
    }
  }

  get_impedance(tag: number) { return this.impedanceCache.get(tag) ? [this.impedanceCache.get(tag)!.re, this.impedanceCache.get(tag)!.im] : [50, 0]; }
  get_currents() { return this.currents; }
  get_max_gain() { return this.maxGainDbi; }

  get_max_field_reference(): number {
    let maxAmp = 0.001;
    for (let x = -2; x <= 10; x += 1) {
      for (let y = -5; y <= 5; y += 1) {
        const { amplitude } = this.calculate_field_and_amplitude(x, y, this.currents[0]?.z / 0.1 || 0, 0);
        if (amplitude > maxAmp) maxAmp = amplitude;
      }
    }
    return maxAmp;
  }

  /**
   * 关键修复：实现距离补偿 (E * r)
   * 这样显示的就是波束的形状，而不是简单的物理场强
   */
  calculate_field_and_amplitude(x: number, y: number, z: number, time_phase: number): { instantaneous: number, amplitude: number } {
    let real_sum = 0;
    let imag_sum = 0;
    const sceneScale = 0.1; 
    const k = (2 * Math.PI * this.frequency) / 299.79;
    const hasGround = this.groundHeight !== null && this.groundHeight > 0;

    const x_m = x * sceneScale;
    const y_m = y * sceneScale;
    const z_m = z * sceneScale;

    // 计算到天线中心的平均距离，用于补偿
    const distToCenter = Math.sqrt(x_m**2 + y_m**2 + (z_m - (this.currents[0]?.z || 0))**2) + 0.1;

    for (const c of this.currents) {
        const r_dir = Math.sqrt((x_m - c.x)**2 + (y_m - c.y)**2 + (z_m - c.z)**2) + 0.05;
        const phase_dir = (c.phase * Math.PI / 180) - (k * r_dir);
        // E 场
        const e_mag = (c.mag * c.length) / r_dir;
        
        real_sum += e_mag * Math.cos(phase_dir);
        imag_sum += e_mag * Math.sin(phase_dir);

        if (hasGround) {
            const r_img = Math.sqrt((x_m - c.x)**2 + (y_m - c.y)**2 + (z_m + c.z)**2) + 0.05;
            const phase_img = (c.phase * Math.PI / 180) - (k * r_img) + Math.PI; 
            const e_mag_img = (c.mag * c.length) / r_img;
            real_sum += e_mag_img * Math.cos(phase_img);
            imag_sum += e_mag_img * Math.sin(phase_img);
        }
    }

    const raw_amplitude = Math.sqrt(real_sum * real_sum + imag_sum * imag_sum);
    
    /**
     * 距离补偿：amplitude = E * r
     * 这样远处的波束如果能量集中，其值会很大（红色）
     * 近处如果没有形成波束，值反而小（蓝色）
     */
    const amplitude = raw_amplitude * distToCenter;
    const instantaneous = amplitude * Math.cos(Math.atan2(imag_sum, real_sum) + time_phase);

    return { instantaneous, amplitude };
  }

  calculate_far_field_pattern_3d(thetas: Float64Array, phis: Float64Array, output: Float64Array) {
    for (let i = 0; i < thetas.length; i++) {
        const t = Math.min(180, Math.max(0, Math.round(thetas[i] * 180 / Math.PI / 5) * 5));
        const p = (Math.round(phis[i] * 180 / Math.PI / 5) * 5 + 360) % 360;
        output[i] = this.patternCache.get(`${t},${p}`) ?? 0.01;
    }
  }

  free() {}
}
