import createNec2Module from "../../public/wasm/nec2c.js";

/**
 * NEC2 Context API Wrapper
 */
export class Nec2Context {
  private wires: any[] = [];
  private sources: any[] = [];
  private frequency: number = 430.0;
  private groundHeight: number | null = null;
  private material: string = "aluminum";
  private patternCache: Map<string, number> = new Map();
  private impedanceCache: Map<number, {re: number, im: number}> = new Map();
  private currents: Array<{
    mag: number, phase: number, x: number, y: number, z: number, length: number,
    ux: number, uy: number, uz: number
  }> = [];
  private maxGainDbi: number = 0;
  private maxGainTheta: number = 90;
  private maxGainPhi: number = 0;
  private center: {x: number, y: number, z: number} = {x: 0, y: 0, z: 0};

  constructor() {}

  initialize(num_wires: number) {
    this.wires = [];
    this.sources = [];
    this.patternCache.clear();
    this.impedanceCache.clear();
    this.currents = [];
  }

  add_wire(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number, radius: number, segments: number, tag: number) {
    const dx = x2 - x1;
    const dy = y2 - y1;
    const dz = z2 - z1;
    const len = Math.sqrt(dx*dx + dy*dy + dz*dz) || 1e-6;
    this.wires.push({ 
        x1, y1, z1, x2, y2, z2, radius, segments, tag, 
        ux: dx/len, uy: dy/len, uz: dz/len 
    });
  }

  set_frequency(mhz: number) { this.frequency = mhz; }
  set_ground(height_lambda: number) { this.groundHeight = height_lambda; }
  set_material(mat: string) { this.material = mat; }
  
  add_voltage_source(tag: number, seg_on_wire: number, real: number, imag: number) {
    this.sources.push({ tag, seg: seg_on_wire, real, imag });
  }

  async calculate() {
    const Module = await (createNec2Module as any)({
      locateFile: (path: string) => `/wasm/${path}`,
      print: () => {}, 
      printErr: () => {}, 
    });

    let nec = `CM Generated by Nec2Context API\nCE\n`;
    for (const w of this.wires) {
      nec += `GW ${w.tag} ${w.segments} ${w.x1.toFixed(5)} ${w.y1.toFixed(5)} ${w.z1.toFixed(5)} ${w.x2.toFixed(5)} ${w.y2.toFixed(5)} ${w.z2.toFixed(5)} ${w.radius.toFixed(6)}\n`;
    }
    
    nec += `GE ${this.groundHeight !== null && this.groundHeight > 0 ? 1 : 0}\n`;
    if (this.material === "aluminum") nec += `LD 5 0 0 0 3.5E7\n`;
    else if (this.material === "stainless_steel") nec += `LD 5 0 0 0 1.1E6\n`;

    if (this.groundHeight !== null && this.groundHeight > 0) {
      nec += `GN 0 0 0 0 13 0.005\n`;
    } else {
      nec += `GN -1\n`;
    }

    for (const s of this.sources) {
      nec += `EX 0 ${s.tag} ${s.seg} 0 ${s.real.toFixed(2)} ${s.imag.toFixed(2)}\n`;
    }
    
    nec += `FR 0 1 0 0 ${this.frequency.toFixed(3)} 0\n`;
    nec += `RP 0 37 73 1 0 0 5 5\n`;
    nec += `EN\n`;

    const inputPath = "/input.nec";
    const outputPath = "/output.out";
    Module.FS.writeFile(inputPath, nec);

    try {
      Module.callMain(["-i", inputPath, "-o", outputPath]);
    } catch (e: any) {
      if (e.name !== "ExitStatus" && e.constructor.name !== "ExitStatus") throw e;
    }

    if (!Module.FS.analyzePath(outputPath).exists) throw new Error("NEC2 failed.");
    const outputData = Module.FS.readFile(outputPath, { encoding: "utf8" });
    this.parseResults(outputData);
  }

  private parseResults(data: string) {
    this.patternCache.clear();
    this.impedanceCache.clear();
    this.currents = [];
    this.maxGainDbi = -99;
    this.maxGainTheta = 90;
    this.maxGainPhi = 0;
    const lines = data.split("\n");
    let section: 'none' | 'impedance' | 'pattern' | 'current' = 'none';

    let currentWireIdx = 0;
    let currentSegInWire = 0;
    let sumX = 0, sumY = 0, sumZ = 0;

    for (let line of lines) {
        line = line.trim();
        if (line.includes("ANTENNA INPUT PARAMETERS")) { section = 'impedance'; continue; }
        if (line.includes("RADIATION PATTERNS")) { section = 'pattern'; continue; }
        if (line.includes("CURRENTS AND LOCATION")) { section = 'current'; continue; }

        const parts = line.split(/\s+/).filter(p => p.length > 0);
        if (parts.length === 0) continue;

        if (section === 'impedance') {
            // Typical line: TAG SEG VOLT_R VOLT_I CURR_R CURR_I IMP_R IMP_I ADM_R ADM_I POWER
            if (parts.length >= 8 && !isNaN(parseInt(parts[0]))) {
                const tag = parseInt(parts[0]);
                this.impedanceCache.set(tag, {
                    re: parseFloat(parts[6]), 
                    im: parseFloat(parts[7])
                });
            }
        }
        if (section === 'current') {
            // Typical line: SEG TAG X Y Z LENGTH ... MAG PHASE
            if (parts.length >= 10 && !isNaN(parseInt(parts[0]))) {
                const wire = this.wires[currentWireIdx];
                if (wire) {
                    const x = parseFloat(parts[2]);
                    const y = parseFloat(parts[3]);
                    const z = parseFloat(parts[4]);
                    this.currents.push({
                        x, y, z,
                        length: parseFloat(parts[5]), 
                        mag: parseFloat(parts[8]), 
                        phase: parseFloat(parts[9]),
                        ux: wire.ux, uy: wire.uy, uz: wire.uz
                    });
                    sumX += x; sumY += y; sumZ += z;
                    currentSegInWire++;
                    if (currentSegInWire >= wire.segments) {
                        currentWireIdx++;
                        currentSegInWire = 0;
                    }
                }
            }
        }
        if (section === 'pattern') {
            // Typical line: THETA PHI VERT_DB HORIZ_DB TOTAL_DB
            if (parts.length >= 5 && !isNaN(parseFloat(parts[0]))) {
                const rawGainDbi = parseFloat(parts[4]);
                if (rawGainDbi > this.maxGainDbi) {
                    this.maxGainDbi = rawGainDbi;
                    this.maxGainTheta = parseFloat(parts[0]);
                    this.maxGainPhi = parseFloat(parts[1]);
                }
                const gain = Math.pow(10, Math.max(-40, rawGainDbi) / 10);
                this.patternCache.set(`${Math.round(parseFloat(parts[0]))},${Math.round(parseFloat(parts[1]))}`, gain);
            }
        }
    }

    if (this.currents.length > 0) {
        this.center = {
            x: sumX / this.currents.length,
            y: sumY / this.currents.length,
            z: sumZ / this.currents.length
        };
    }
  }

  get_impedance(tag: number) { return this.impedanceCache.get(tag) ? [this.impedanceCache.get(tag)!.re, this.impedanceCache.get(tag)!.im] : [50, 0]; }
  get_currents() { return this.currents; }
  get_max_gain() { return this.maxGainDbi; }
  get_max_gain_direction() { return { theta: this.maxGainTheta, phi: this.maxGainPhi }; }
  get_center() { return this.center; }
  get_frequency() { return this.frequency; }

  get_max_field_reference(): number {
    const lambda = 299.79 / this.frequency;
    const r_sample = Math.max(lambda, 10.0);

    const thetaRad = (this.maxGainTheta * Math.PI) / 180;
    const phiRad = (this.maxGainPhi * Math.PI) / 180;

    const x = this.center.x + r_sample * Math.sin(thetaRad) * Math.cos(phiRad);
    const y = this.center.y + r_sample * Math.sin(thetaRad) * Math.sin(phiRad);
    const z = this.center.z + r_sample * Math.cos(thetaRad);

    const { amplitude } = this.calculate_field_and_amplitude(x, y, z, 0);
    let maxAmp = amplitude * (r_sample + 0.1);

    if (maxAmp < 0.0001) {
        for (let t = 0; t <= Math.PI; t += Math.PI / 6) {
            for (let p = 0; p < Math.PI * 2; p += Math.PI / 6) {
                const tx = this.center.x + r_sample * Math.sin(t) * Math.cos(p);
                const ty = this.center.y + r_sample * Math.sin(t) * Math.sin(p);
                const tz = this.center.z + r_sample * Math.cos(t);
                if (this.groundHeight !== null && this.groundHeight > 0 && tz < 0) continue;
                const { amplitude: amp } = this.calculate_field_and_amplitude(tx, ty, tz, 0);
                const comp = amp * (r_sample + 0.1);
                if (comp > maxAmp) maxAmp = comp;
            }
        }
    }
    
    console.log(`[NEC2] MaxGain: ${this.maxGainDbi.toFixed(2)}dBi at T=${this.maxGainTheta} P=${this.maxGainPhi}, RefField: ${maxAmp.toFixed(4)}`);
    return Math.max(0.001, maxAmp);
  }

  /**
   * 计算指定坐标点（物理单位米）的瞬时场强和振幅
   */
  calculate_field_and_amplitude(x: number, y: number, z: number, time_phase: number): { instantaneous: number, amplitude: number } {
    let ex_re = 0, ex_im = 0;
    let ey_re = 0, ey_im = 0;
    let ez_re = 0, ez_im = 0;

    const k = (2 * Math.PI * this.frequency) / 299.79;
    const hasGround = this.groundHeight !== null && this.groundHeight > 0;

    for (const c of this.currents) {
        const dx = x - c.x;
        const dy = y - c.y;
        const dz = z - c.z;
        const r_dist = Math.sqrt(dx*dx + dy*dy + dz*dz) + 0.01;
        const rx = dx / r_dist, ry = dy / r_dist, rz = dz / r_dist;

        const dot = c.ux * rx + c.uy * ry + c.uz * rz;
        const lp_x = c.ux - dot * rx;
        const lp_y = c.uy - dot * ry;
        const lp_z = c.uz - dot * rz;

        const phase = (c.phase * Math.PI / 180) - (k * r_dist);
        const factor = (c.mag * c.length) / r_dist;
        const cosP = Math.cos(phase);
        const sinP = Math.sin(phase);

        ex_re += factor * lp_x * cosP;
        ex_im += factor * lp_x * sinP;
        ey_re += factor * lp_y * cosP;
        ey_im += factor * lp_y * sinP;
        ez_re += factor * lp_z * cosP;
        ez_im += factor * lp_z * sinP;

        if (hasGround) {
            const dz_img = z + c.z;
            const r_img = Math.sqrt(dx*dx + dy*dy + dz_img*dz_img) + 0.01;
            const rxi = dx / r_img, ryi = dy / r_img, rzi = dz_img / r_img;
            
            const iux = -c.ux, iuy = -c.uy, iuz = c.uz;
            const doti = iux * rxi + iuy * ryi + iuz * rzi;
            const lpix = iux - doti * rxi;
            const lpiy = iuy - doti * ryi;
            const lpiz = iuz - doti * rzi;

            const phase_i = (c.phase * Math.PI / 180) - (k * r_img);
            const factor_i = (c.mag * c.length) / r_img;
            const cosPi = Math.cos(phase_i);
            const sinPi = Math.sin(phase_i);

            ex_re += factor_i * lpix * cosPi;
            ex_im += factor_i * lpix * sinPi;
            ey_re += factor_i * lpiy * cosPi;
            ey_im += factor_i * lpiy * sinPi;
            ez_re += factor_i * lpiz * cosPi;
            ez_im += factor_i * lpiz * sinPi;
        }
    }

    const amplitude = Math.sqrt(
        ex_re*ex_re + ex_im*ex_im + 
        ey_re*ey_re + ey_im*ey_im + 
        ez_re*ez_re + ez_im*ez_im
    );

    const instX = ex_re * Math.cos(time_phase) - ex_im * Math.sin(time_phase);
    const instY = ey_re * Math.cos(time_phase) - ey_im * Math.sin(time_phase);
    const instZ = ez_re * Math.cos(time_phase) - ez_im * Math.sin(time_phase);
    const instantaneous = instX + instY + instZ;

    return { instantaneous, amplitude };
  }
  
  calculate_far_field_pattern_3d(thetas: Float64Array, phis: Float64Array, output: Float64Array) {
    for (let i = 0; i < thetas.length; i++) {
        const t = Math.min(180, Math.max(0, Math.round(thetas[i] * 180 / Math.PI / 5) * 5));
        const p = (Math.round(phis[i] * 180 / Math.PI / 5) * 5 + 360) % 360;
        output[i] = this.patternCache.get(`${t},${p}`) ?? 0.01;
    }
  }

  free() {}
}
